version: '3'
networks:
  dathoc-spark-net:
    external:
      name: dathoc-spark-net
services:
  spark-master:
    image: dathoc/spark-master:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - /home/kj/kafka-spark-flink-example/out/artifacts/kafka_spark_flink_example_jar3/kafka-spark-flink-example.jar:/tmp/kafka-spark-flink-example.jar:rw,z
      - /home/kj/kafka-spark-flink-example/out/artifacts/kafka_spark_flink_example_jar/wc.jar:/tmp/wc.jar:rw,z
      - /home/kj/kafka-spark-flink-example/out/artifacts/kafka_spark_flink_example_jar/WordCount.jar:/tmp/WordCount.jar:rw,z      
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - dathoc-spark-net  
  spark-worker-1:
    image: dathoc/spark-worker:latest
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - /home/kj/kafka-spark-flink-example/out/artifacts/kafka_spark_flink_example_jar3/kafka-spark-flink-example.jar:/tmp/kafka-spark-flink-example.jar:rw,z
      - /home/kj/kafka-spark-flink-example/out/artifacts/kafka_spark_flink_example_jar/wc.jar:/tmp/wc.jar:rw,z
      - /home/kj/kafka-spark-flink-example/out/artifacts/kafka_spark_flink_example_jar/WordCount.jar:/tmp/WordCount.jar:rw,z
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - dathoc-spark-net  
  spark-worker-2:
    image: dathoc/spark-worker:latest
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - /home/kj/kafka-spark-flink-example/out/artifacts/kafka_spark_flink_example_jar3/kafka-spark-flink-example.jar:/tmp/kafka-spark-flink-example.jar:rw,z
      - /home/kj/kafka-spark-flink-example/out/artifacts/kafka_spark_flink_example_jar/wc.jar:/tmp/wc.jar:rw,z
      - /home/kj/kafka-spark-flink-example/out/artifacts/kafka_spark_flink_example_jar/WordCount.jar:/tmp/WordCount.jar:rw,z      
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - dathoc-spark-net
  spark-history-server:
    image: dathoc/spark-history-server:latest
    container_name: spark-history-server
    depends_on:
      - spark-master
    ports:
      - "18081:18081"
    volumes:
      - /tmp/spark-events-local:/tmp/spark-events
    networks:
      - dathoc-spark-net
  spark-submit:
    image: dathoc/spark-submit:latest
    container_name: spark-submit
    depends_on:
      - spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - /home/kj/kafka-spark-flink-example/out/artifacts/kafka_spark_flink_example_jar3/kafka-spark-flink-example.jar:/tmp/kafka-spark-flink-example.jar:rw,z
      - /home/kj/kafka-spark-flink-example/out/artifacts/kafka_spark_flink_example_jar/wc.jar:/tmp/wc.jar:rw,z
      - /home/kj/kafka-spark-flink-example/out/artifacts/kafka_spark_flink_example_jar/WordCount.jar:/tmp/WordCount.jar:rw,z   
      - /home/kj/Downloads/hp.txt:/tmp/input/hp.txt:rw,z  
      - ./submit/submit.sh:/submit.sh:rw,z
    networks:
      - dathoc-spark-net 